import APNS
import APNSCore
import AsyncHTTPClient
import Vapor
import VaporAPNS
import WebPush

struct PushResult {
    let success: Bool
    let error: String?
}

enum PushProviderConfigError: LocalizedError, Equatable {
    case invalidValue(String, String, String)
    case invalidURL(String, String)
    case missingRequiredValue(String)

    var errorDescription: String? {
        switch self {
        case let .invalidValue(key, value, allowed):
            "Invalid value for \(key): \(value). Allowed values: \(allowed)"
        case let .invalidURL(key, value):
            "Invalid URL value for \(key): \(value)"
        case let .missingRequiredValue(key):
            "Missing required configuration value for \(key)"
        }
    }
}

enum APNSPushEnvironment: String, CaseIterable, Equatable {
    case development
    case production
}

enum APNSPushMode: Equatable {
    case direct(APNSDirectConfiguration)
    case relay(APNSRelayConfiguration)
}

struct APNSDirectConfiguration: Equatable {
    let keyPath: String
    let keyID: String
    let teamID: String
    let bundleID: String
    let environment: APNSPushEnvironment
}

struct APNSRelayConfiguration: Equatable {
    static let defaultBaseURL = URL(string: "https://pingd.dev")!

    let baseURL: URL
    let authToken: String

    var endpointURL: URL {
        baseURL.appending(path: "apns").appending(path: "push")
    }
}

struct WebPushConfiguration: Equatable {
    let vapidConfiguration: VAPID.Configuration
}

struct PingdAPNSPayload: Codable, Sendable {
    let messageID: UUID
    let topic: String
    let priority: UInt8
    let tags: [String]?
    let time: Date
}

struct PingdWebPushPayload: Codable, Sendable {
    struct Notification: Codable, Sendable {
        let title: String
        let body: String
    }

    struct DataPayload: Codable, Sendable {
        let messageID: UUID
        let topic: String
        let subtitle: String?
        let priority: UInt8
        let tags: [String]?
        let time: Date
    }

    let notification: Notification
    let data: DataPayload
}

struct RelayPushRequest: Content {
    let deviceToken: String
    let payload: MessagePayload
    let metadata: PingdAPNSPayload
    let expiresAt: Date?
}

struct PushProvider {
    let webPushVAPIDKey: @Sendable () -> String?
    let send: @Sendable (
        _ deviceToken: String,
        _ pushType: PushType,
        _ payload: MessagePayload,
        _ metadata: PingdAPNSPayload,
        _ expiresAt: Date?
    ) async throws -> PushResult
}

extension PushProvider {
    static func loadWebPushConfiguration(
        environmentVariables: [String: String] = ProcessInfo.processInfo.environment
    ) throws -> WebPushConfiguration? {
        guard let rawConfiguration = trimmedValue(
            for: "PINGD_WEBPUSH_VAPID_CONFIG",
            environmentVariables: environmentVariables
        ) else {
            return nil
        }

        do {
            let configuration = try JSONDecoder().decode(
                VAPID.Configuration.self,
                from: Data(rawConfiguration.utf8)
            )
            return WebPushConfiguration(vapidConfiguration: configuration)
        } catch {
            throw PushProviderConfigError.invalidValue(
                "PINGD_WEBPUSH_VAPID_CONFIG",
                "invalid JSON",
                "VAPID configuration JSON generated by vapid-key-generator"
            )
        }
    }

    static func loadAPNSConfiguration(
        environmentVariables: [String: String] = ProcessInfo.processInfo.environment
    ) throws -> APNSPushMode? {
        guard let modeString = trimmedValue(for: "PINGD_APNS_MODE", environmentVariables: environmentVariables) else {
            return nil
        }

        switch modeString {
        case "direct":
            return try .direct(loadDirectAPNSConfiguration(environmentVariables: environmentVariables))
        case "relay":
            return try .relay(loadRelayAPNSConfiguration(environmentVariables: environmentVariables))
        default:
            throw PushProviderConfigError.invalidValue("PINGD_APNS_MODE", modeString, "direct, relay")
        }
    }

    static func apns(application: Application, config: APNSDirectConfiguration, logger: Logger) -> Self {
        PushProvider(
            webPushVAPIDKey: { nil },
            send: { deviceToken, pushType, payload, metadata, expiresAt in
                guard pushType == .apns else {
                    return PushResult(success: false, error: "APNS provider cannot handle \(pushType) push type")
                }

                let containerID: APNSContainers.ID = switch config.environment {
                case .development: .development
                case .production: .production
                }

                let expiration: APNSNotificationExpiration = expiresAt.map {
                    .timeIntervalSince1970InSeconds(Int($0.timeIntervalSince1970))
                } ?? .immediately

                do {
                    let client = await application.apns.client(containerID)
                    let alert = APNSAlertNotificationContent(
                        title: payload.title.map { .raw($0) },
                        subtitle: payload.subtitle.map { .raw($0) },
                        body: .raw(payload.body)
                    )
                    let notification = APNSAlertNotification(
                        alert: alert,
                        expiration: expiration,
                        priority: .immediately,
                        topic: config.bundleID,
                        payload: metadata,
                        sound: .default
                    )
                    try await client.sendAlertNotification(notification, deviceToken: deviceToken)
                    return PushResult(success: true, error: nil)
                } catch {
                    logger.error("[PushProvider.apns] Failed to send: \(error)")
                    return PushResult(success: false, error: error.localizedDescription)
                }
            }
        )
    }

    static func relay(config: APNSRelayConfiguration, logger: Logger) -> Self {
        PushProvider(
            webPushVAPIDKey: { nil },
            send: { deviceToken, pushType, payload, metadata, expiresAt in
                guard pushType == .apns else {
                    return PushResult(success: false, error: "Relay provider cannot handle \(pushType) push type")
                }

                var request = HTTPClientRequest(url: config.endpointURL.absoluteString)
                request.method = .POST
                request.headers.add(name: "Content-Type", value: "application/json")
                request.headers.add(name: "Authorization", value: "Bearer \(config.authToken)")

                let body = RelayPushRequest(
                    deviceToken: deviceToken,
                    payload: payload,
                    metadata: metadata,
                    expiresAt: expiresAt
                )
                let encoder = JSONEncoder()
                encoder.dateEncodingStrategy = .iso8601
                let data = try encoder.encode(body)
                request.body = .bytes(data)

                let response = try await HTTPClient.shared.execute(request, timeout: .seconds(30))

                if response.status == .ok {
                    return PushResult(success: true, error: nil)
                } else {
                    let responseBody = try? await response.body.collect(upTo: 1024 * 10)
                    let message = responseBody.map { String(buffer: $0) } ?? "HTTP \(response.status.code)"
                    logger.error("[PushProvider.relay] Failed: \(message)")
                    return PushResult(success: false, error: message)
                }
            }
        )
    }

    static func webPush(config: WebPushConfiguration, logger: Logger) -> Self {
        let manager = WebPushManager(
            vapidConfiguration: config.vapidConfiguration,
            backgroundActivityLogger: logger
        )

        return PushProvider(
            webPushVAPIDKey: {
                "\(manager.nextVAPIDKeyID)"
            },
            send: { deviceToken, pushType, payload, metadata, expiresAt in
                guard pushType == .webPush else {
                    return PushResult(success: false, error: "Web Push provider cannot handle \(pushType) push type")
                }

                do {
                    let subscriber = try JSONDecoder().decode(Subscriber.self, from: Data(deviceToken.utf8))
                    let message = PingdWebPushPayload(
                        notification: .init(
                            title: payload.title ?? metadata.topic,
                            body: payload.body
                        ),
                        data: .init(
                            messageID: metadata.messageID,
                            topic: metadata.topic,
                            subtitle: payload.subtitle,
                            priority: metadata.priority,
                            tags: metadata.tags,
                            time: metadata.time
                        )
                    )
                    let data = try JSONEncoder().encode(message)
                    let expiration = webPushExpiration(from: expiresAt)
                    let urgency = webPushUrgency(for: metadata.priority)
                    try await manager.send(
                        data: data,
                        to: subscriber,
                        encodableDeduplicationTopic: metadata.messageID.uuidString,
                        expiration: expiration,
                        urgency: urgency,
                        logger: logger
                    )
                    return PushResult(success: true, error: nil)
                } catch is BadSubscriberError {
                    logger.warning("[PushProvider.webPush] Bad subscriber")
                    return PushResult(success: false, error: "Bad Web Push subscriber")
                } catch is MessageTooLargeError {
                    logger.warning("[PushProvider.webPush] Message too large")
                    return PushResult(success: false, error: "Web Push message too large")
                } catch {
                    logger.error("[PushProvider.webPush] Failed to send: \(error)")
                    return PushResult(success: false, error: error.localizedDescription)
                }
            }
        )
    }

    static func routed(apns: PushProvider?, webPush: PushProvider?, logger: Logger) -> Self {
        PushProvider(
            webPushVAPIDKey: {
                webPush?.webPushVAPIDKey()
            },
            send: { deviceToken, pushType, payload, metadata, expiresAt in
                switch pushType {
                case .apns:
                    guard let apns else {
                        return PushResult(success: false, error: "APNS provider is not configured")
                    }
                    return try await apns.send(deviceToken, pushType, payload, metadata, expiresAt)
                case .webPush:
                    guard let webPush else {
                        return PushResult(success: false, error: "Web Push provider is not configured")
                    }
                    return try await webPush.send(deviceToken, pushType, payload, metadata, expiresAt)
                case .fcm:
                    logger.warning("[PushProvider.routed] FCM provider is not configured")
                    return PushResult(success: false, error: "FCM provider is not configured")
                }
            }
        )
    }

    static func mock(logger: Logger) -> Self {
        PushProvider(
            webPushVAPIDKey: { nil },
            send: { _, pushType, payload, metadata, _ in
                logger.info("[PushProvider.mock] \(pushType) | topic=\(metadata.topic) priority=\(metadata.priority) title=\(payload.title ?? "-") body=\(payload.body)")
                return PushResult(success: true, error: nil)
            }
        )
    }
}

private func webPushExpiration(from expiresAt: Date?) -> WebPushManager.Expiration {
    guard let expiresAt else {
        return .recommendedMaximum
    }

    let seconds = max(0, Int(expiresAt.timeIntervalSinceNow.rounded(.up)))
    let cap = 30 * 24 * 60 * 60
    return .seconds(min(seconds, cap))
}

private func webPushUrgency(for priority: UInt8) -> WebPushManager.Urgency {
    switch priority {
    case 3:
        .high
    case 2:
        .normal
    default:
        .low
    }
}

private func loadDirectAPNSConfiguration(
    environmentVariables: [String: String]
) throws -> APNSDirectConfiguration {
    try APNSDirectConfiguration(
        keyPath: requiredValue(for: "PINGD_APNS_KEY_PATH", environmentVariables: environmentVariables),
        keyID: requiredValue(for: "PINGD_APNS_KEY_ID", environmentVariables: environmentVariables),
        teamID: requiredValue(for: "PINGD_APNS_TEAM_ID", environmentVariables: environmentVariables),
        bundleID: requiredValue(for: "PINGD_APNS_BUNDLE_ID", environmentVariables: environmentVariables),
        environment: parseAPNSEnvironment(
            for: "PINGD_APNS_ENV",
            environmentVariables: environmentVariables
        ) ?? .production
    )
}

private func loadRelayAPNSConfiguration(
    environmentVariables: [String: String]
) throws -> APNSRelayConfiguration {
    let endpointString = trimmedValue(
        for: "PINGD_APNS_RELAY_BASE_URL",
        environmentVariables: environmentVariables
    )

    let baseURL: URL
    if let endpointString {
        guard let parsedURL = URL(string: endpointString) else {
            throw PushProviderConfigError.invalidURL("PINGD_APNS_RELAY_BASE_URL", endpointString)
        }
        baseURL = parsedURL
    } else {
        baseURL = APNSRelayConfiguration.defaultBaseURL
    }

    return try APNSRelayConfiguration(
        baseURL: baseURL,
        authToken: requiredValue(for: "PINGD_APNS_RELAY_TOKEN", environmentVariables: environmentVariables)
    )
}

private func requiredValue(
    for key: String,
    environmentVariables: [String: String]
) throws -> String {
    guard let value = trimmedValue(for: key, environmentVariables: environmentVariables) else {
        throw PushProviderConfigError.missingRequiredValue(key)
    }
    return value
}

private func trimmedValue(
    for key: String,
    environmentVariables: [String: String]
) -> String? {
    guard let rawValue = environmentVariables[key]?.trimmingCharacters(in: .whitespacesAndNewlines),
          !rawValue.isEmpty
    else {
        return nil
    }

    return rawValue
}

private func parseAPNSEnvironment(
    for key: String,
    environmentVariables: [String: String]
) throws -> APNSPushEnvironment? {
    guard let value = trimmedValue(for: key, environmentVariables: environmentVariables) else {
        return nil
    }

    guard let environment = APNSPushEnvironment(rawValue: value) else {
        let allowed = APNSPushEnvironment.allCases.map(\.rawValue).joined(separator: ", ")
        throw PushProviderConfigError.invalidValue(key, value, allowed)
    }

    return environment
}
